# Generated by Django 6.0 on 2026-01-15 15:41

import db.document
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('License', 'License'), ('Contract', 'Contract'), ('Report', 'Report'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('source_url', models.URLField()),
                ('ocr_content', models.JSONField()),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('issuing_affiliation', models.CharField(max_length=200)),
                ('settings', models.JSONField(default=db.document.default_doc_settings)),
                ('issue_at', models.DateTimeField(auto_now=True)),
                ('expiry_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to='api.user')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to='api.user')),
            ],
            options={
                'db_table': 'document',
            },
        ),
    ]
