# Generated by Django 6.0 on 2026-03-10 20:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_blockchain_tx_hash_document_document_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('upload', 'upload'), ('check', 'check'), ('shared', 'shared')], default='upload', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.document')),
                ('doc_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_activities', to='api.user')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='api.user')),
            ],
            options={
                'db_table': 'activity',
            },
        ),
    ]
